# Generated by Django 4.2.2 on 2023-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nothing', max_length=100, verbose_name='Title')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
    ]
