# Generated by Django 4.2.2 on 2023-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.CharField(default='Nothing', max_length=100, verbose_name='Title'),
        ),
    ]
